### ISSUE TITLE
The tools have a problem, cant' pull images and save toa  *.tar.gz file.

### ISSUE THREAD

**Issue by sober-wang** [zhangguanzhang/dp#2]
[root@my-mesos-slave pkg]# ./dp pull filebeat-image.tar.gz docker.elastic.co/beats/filebeat:7.6.2
2020/05/09 12:16:02 Save failed: unmarshal err|invalid character '<' looking for beginning of value
[root@my-mesos-slave pkg]# uname -a
Linux my-mesos-slave 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[root@my-mesos-slave pkg]#

**Comment by zhangguanzhang** [comment]
这个是由于azk8s.cn这个代理关了，我有空更新了后发布新的，这个issue先别关，我新的发布了后我自己会关闭这个issue的

**Comment by zhangguanzhang** [comment]
不对，这个是es的那个，应该是网络问题导致的

**Comment by zhangguanzhang** [comment]
这个es的仓库我用bash脚本在travis-ci里写了同步过程，可以到我dockerhub上看
https://hub.docker.com/r/zhangguanzhang/docker.elastic.co.beats.filebeat/tags
这个是已经同步过的列表
https://github.com/zhangguanzhang/k8s_bin-docker_cp/blob/develop/sync/docker.elastic.co/synced
这个是同步的脚本代码
https://github.com/zhangguanzhang/k8s_bin-docker_cp/blob/master/bash/docker.elastic.co/elastic.co.sh

**Comment by zhangguanzhang** [comment]
你可以
```
docker pull zhangguanzhang/docker.elastic.co.beats.filebeat:7.6.2
docker tag xxx
docker push 到你内网或者你自己的dockerhub
```
